#!/usr/bin/env zsh

function _zen_cmd_init() {

    if [[ -n $ZEN_INITIALIZED ]]; then
        echo "$0: Already initialized" >&2
        return 1
    fi

    if [[ ! -d $ZEN_PLUGIN_DIR ]]; then
        mkdir -p $ZEN_PLUGIN_DIR
    fi

    autoload -Uz compinit
    compinit

    autoload -Uz zen-utils
    zen-utils

    ZEN_INITIALIZED=1
}

function _zen_cmd_load() {

    # TODO: Support loading plugin by path
    # TODO: Support loading plugin by URL (git clone)

    if [[ $# -eq 0 ]]; then
        echo "$0: Plugin name required" >&2
        return 1
    fi

    local plugin_name=$1

    # Try to load plugin as single file
    local plugin_file=${ZEN_PLUGIN_DIR}/${plugin_name}.zsh
    if [[ -r $plugin_file ]]; then
        source $plugin_file
        return
    fi

    # Try to load plugin from a dir
    local plugin_file=${ZEN_PLUGIN_DIR}/${plugin_name}/${plugin_name}.plugin.zsh
    if [[ -r $plugin_file ]]; then
        source $plugin_file
        return
    fi
}

# TODO: Use zparseopts

if [[ $# -eq 0 ]]; then
    echo "$0: Subcommand required" >&2
    return 1
fi

local command=$1
shift
case $command in
init)
    _zen_cmd_init "$@"
    ;;
load)
    _zen_cmd_load "$@"
    ;;
*)
    echo "$0: Invalid subcommand: $command" >&2
    return 1
    ;;
esac
